export const REVIEW_LABELS = {
  REVIEW_ID: 'レビューID',
  VISIT_DATE: '訪問日',
  GIRL_NAME: '女の子名',
  TOTAL_SCORE: '総合評価',
  SCORE_GIRL: '女の子',
  SCORE_PLAY: 'プレイ',
  SCORE_PRICE: '料金',
  SCORE_STAFF: 'スタッフ',
  SCORE_PHOTO: '写真',
  TITLE: 'タイトル',
  BODY: '本文',
  POST_DATE: '掲載日',
} as const;

export const REVIEW_HEADERS = [
  REVIEW_LABELS.REVIEW_ID,
  REVIEW_LABELS.VISIT_DATE,
  REVIEW_LABELS.GIRL_NAME,
  REVIEW_LABELS.TOTAL_SCORE,
  REVIEW_LABELS.SCORE_GIRL,
  REVIEW_LABELS.SCORE_PLAY,
  REVIEW_LABELS.SCORE_PRICE,
  REVIEW_LABELS.SCORE_STAFF,
  REVIEW_LABELS.SCORE_PHOTO,
  REVIEW_LABELS.TITLE,
  REVIEW_LABELS.BODY,
  REVIEW_LABELS.POST_DATE,
] as const;
